### ISSUE TITLE
Can't resolve 'error-causes'

### ISSUE THREAD

**Issue by oliver-day** [paralleldrive/error-causes#10]
Version: `1.1.0`

I'm running into an `MODULE_NOT_FOUND` error when attempting to import the `error-causes` module:

<img width="536" alt="Screen Shot 2022-10-23 at 10 34 54 AM" src="https://user-images.githubusercontent.com/18020181/197406901-0479b08d-476c-4a76-852a-e33efe18d3a6.png">

I believe the `package.json` for `error-causes` needs an updated value for `main` and/or `exports` properties.

**Comment by ericelliott** [comment]
I forgot to include an `index.js` file in the project root. Do you want to add it and open a PR?
